[omeka]
items_url = http://<IP_Address>/omeka/api/items
site_url = http://<IP_Address>/omeka/s/terracotta/item/
# Optional Omeka API credentials. Leave blank for a public API.
api_key_identity =
api_key_credential =
