[omeka]
items_url = http://94.103.163.196/omeka/api/items
site_url = http://94.103.163.196/omeka/s/terracotta/item/
# Optional Omeka API credentials. Leave blank for a public API.
api_key_identity =
api_key_credential =
